FROM python:3.11-alpine

# Update the package list and install libpq-dev and gcc
RUN apk update && \
    apk add --no-cache \
        libpq \
        gcc \
        musl-dev \
        postgresql-dev

WORKDIR /app

COPY requirements.txt requirements.txt

RUN pip install --upgrade pip && \
    pip install -r requirements.txt

COPY . .

EXPOSE 8000

CMD ["python", "app.py"]
